name: Publish to NPM on Release Commit

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: startsWith(github.event.head_commit.message, 'Release ')
    uses: adobe/aio-reusable-workflows/.github/workflows/on-push-publish-to-npm.yml@main
    secrets:
      ADOBE_BOT_NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}

