name: version-bump-publish

on:
  workflow_call:

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm install
          npm test
      - name: bump and pub
        if: ${{ github.event.inputs.level != '' }}
        run: |
          npm version ${{ github.event.inputs.level }}
          git push
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          access: 'public'
